#!/usr/bin/env python3
"""Regenerate tests/fixtures/config_<case>.yaml and tests/reference/<case>/.

Run this whenever tests/cases.py's overrides change, or when config.yaml's
own schema changes in a way that could affect these cases (see
tests/README.md for the full explanation):

    python3 tests/generate_reference.py

This OVERWRITES the checked-in fixtures and reference outputs. Review the
resulting `git diff` before committing -- an unexpected diff here usually
means either a real behavior change (expected, if you're intentionally
updating the physics/numerics) or an accidental regression (not expected).
"""

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cases import CASES
from helpers import FIXTURES_DIR, REFERENCE_DIR, build_variant_config, run_case, write_variant_config


def main() -> None:
    for case in CASES:
        name = case["name"]
        print(f"=== {name}: {case['description']} ===")

        config_dict = build_variant_config(case["overrides"])
        fixture_path = FIXTURES_DIR / f"config_{name}.yaml"
        write_variant_config(config_dict, fixture_path, name)
        print(f"  wrote fixture: {fixture_path}")

        ref_dir = REFERENCE_DIR / name
        if ref_dir.exists():
            shutil.rmtree(ref_dir)

        csv_path, meta_path, state_path = run_case(fixture_path, ref_dir)

        # Lattice PNGs are always generated by run_simulation but are not part
        # of the numerical regression check (matplotlib rendering is not
        # guaranteed pixel-stable across versions/fonts); drop them so the
        # committed reference only holds what the tests actually compare.
        images_dir = ref_dir / "images"
        if images_dir.exists():
            shutil.rmtree(images_dir)

        print(f"  csv:   {csv_path}")
        print(f"  meta:  {meta_path}")
        print(f"  state: {state_path}")

    print("\nDone. Review `git status`/`git diff` under tests/ before committing.")


if __name__ == "__main__":
    main()
